spring:
  port: 8005
  application:
    name: cloud-email-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.114:3306/lykj?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: anxin521.
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  mail:
    host: smtp.mxhichina.com #阿里企业邮箱发送邮件服务器
    username: pd@leiyankeji.com #发送邮件的邮箱地址
    password: 123gxy@11  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465
    from: pd@leiyankeji.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

