server:
  port: 8002

spring:
  application:
    name: cloud-ai-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.114:3306/lykj?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: anxin521.
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.lykj.com.lykj.springcloud.data.entities    # 所有Entity别名类所在包

